// app/layout.js (or layout.tsx)
import ApolloWrapper from "../../lib/ApolloWrapper";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import Footer from "../(main)/footer/page";
// import Header from "../(main)/header/page";
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* <Header /> */}
        <ApolloWrapper>
        <Toaster position="top-right" />
        {children}
        </ApolloWrapper>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
