services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asim123
      POSTGRES_DB: PlumaDB
    volumes:
      - pgdata:/var/lib/postgresql/data



  backend:
    build:
      context: ./backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres


  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    environment:
      - NEXT_PUBLIC_GRAPHQL_ENDPOINT= http://backend:5000/graphql
    depends_on:
      - backend


volumes:
  pgdata:
