import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
// import Header from "../header/page";
// import Footer from "../footer/page";
// import Footer from '../(main)/footer/page'
import Footer from '../component/FooterWrapper'
// import Header from '../(main)/header/page'
import Header from "../component/HeaderWrapper";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <Header />
      {children}
      <Footer />
    </div>
  );
}
