name: CI/CD pipelines

on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3


            - name: Login with Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_PASSWORD}}

            - name: Build and Push Backend Docker Images
              uses: docker/build-push-action@v5
              with:
                context: ./backend
                push: true
                tags: ${{secrets.DOCKER_USERNAME}}/pluma-backend:latest

            - name: Buld and Push Frontend Docker Image
              uses: docker/build-push-action@v5
              with:
                context: ./frontend
                push: true
                tags: ${{secrets.DOCKER_USERNAME}}/pluma-frontend:latest